### ISSUE TITLE
msal-browser and omniauth for rails api only backend

### ISSUE THREAD

**Issue by arpu** [microsoftgraph/msgraph-sample-rubyrailsapp#134]
Hi,

not sure if this is the right place to ask, but what is the best way to use omniauth and msal.browser msal-react for a rails api with omniauth? 

Thanks!

**Comment by jasonjoh** [comment]
@arpu you're right, this isn't the best place to ask. You will probably have more luck on [Microsoft Q&A](https://learn.microsoft.com/answers/tags/455/entra-id), tagging your question with `Microsoft Entra ID`.
