### ISSUE TITLE
AuthError after verification from Microsoft

### ISSUE THREAD

**Issue by ajitscorpio** [microsoftgraph/msgraph-sample-rubyrailsapp#136]
I just followed the instructions and got app up and running. app is redirecting me to Microsoft portal correctly. After I validate and authorize it redirects me back to my specified callback URL but getting following error:

#<SnakyHash::StringKeyed code="InvalidAuthenticationToken" inner_error=#<SnakyHash::StringKeyed client_request_id="968d871c-55e9-4508-8851-4bae0089d766" date="2023-12-05T17:18:49" request_id="968d871c-55e9-4508-8851-4bae0089d766"> message="CompactToken parsing failed with error code: 80049217">:
{"error":{"code":"InvalidAuthenticationToken","message":"CompactToken parsing failed with error code: 80049217","innerError":{"date":"2023-12-05T17:18:49","request-id":"968d871c-55e9-4508-8851-4bae0089d766","client-request-id":"968d871c-55e9-4508-8851-4bae0089d766"}}}

Any ideas?

**Comment by jasonjoh** [comment]
Something's wrong with the access token in your case. Just to make sure I ran the current code myself and it worked as expected.

I would add some debug code in application_controller.rb to print the `token_hash` value, see what's actually being stored in the session.
