### ISSUE TITLE
Calendar page returns a TimeZone error

### ISSUE THREAD

**Issue by drnic** [microsoftgraph/msgraph-sample-rubyrailsapp#195]
### Calendar page returns a TimeZone error

```
Microsoft Graph returned an error getting events.

{"error"=>{"code"=>"TimeZoneNotSupportedException", "message"=>"A valid TimeZone value must be specified. The following TimeZone value is not supported: '[]'."}}
```

### To Reproduce

1. I followed the instructions in readme
2. I logged in as a work email-based MS account
3. I clicked on "Calendar" nav menu
4. Error

### Expected behavior

No error.

### Screenshots

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/a58cc7ef-9fb4-4ed7-989b-cdee76ad36da">

### Desktop

- MacOS
- ruby 3.3.5

**Comment by jasonjoh** [comment]
@drnic I've seen this in the past when your account didn't have a time zone set in Outlook settings. Sometimes just the act of opening the settings fixes it. Can you go to outlook.office.com and access your settings?

![image](https://github.com/user-attachments/assets/a7e01d9f-4add-465a-a471-4b33a921a8b0)
