### ISSUE TITLE
Getting Net::OpenTimeout

### ISSUE THREAD

**Issue by Mohammed-Balfaqih** [microsoftgraph/msgraph-sample-rubyrailsapp#72]
after log-in with my Hotmail & password, I'm getting **Net::OpenTimeout** 

it's caused by calling:
`@raw_info ||= access_token.get('https://graph.microsoft.com/v1.0/me?$select=displayName,mail,mailboxSettings,userPrincipalName').parsed`

**Comment by Mohammed-Balfaqih** [comment]
@jasonjoh any idea?

**Comment by jasonjoh** [comment]
Check if it is a service issue with Graph. Go to https://developer.microsoft.com/en-us/graph/graph-explorer and sign in with that same account, then try running the same query: `https://graph.microsoft.com/v1.0/me?$select=displayName,mail,mailboxSettings,userPrincipalName`

**Comment by jasonjoh** [comment]
Just to be sure I tried this just now with my personal Outlook.com account and the call succeeded.

**Comment by Mohammed-Balfaqih** [comment]
@jasonjoh I tried to call from the:  https://developer.microsoft.com/en-us/graph/graph-explorer
and the call succeeded as well. so what do you think the issue will be? 🤔 

This is the logs if it can help:
`OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".
Started GET "/auth/microsoft_graph_auth/callback?code=M.R3_BAY.51cfdb67-748b-e3c3-9f23-c286c558ab20&state=72d207ce617bc770ecf66d55ed725ffe2d13f18cb1a3f5da" for ::1 at 2023-02-01 17:07:53 +0300
D, [2023-02-01T17:07:53.859309 #68868] DEBUG -- omniauth: (microsoft_graph_auth) Callback phase initiated.
OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".
E, [2023-02-01T17:08:29.384032 #68868] ERROR -- omniauth: (microsoft_graph_auth) Authentication failure! Net::OpenTimeout: OAuth2::ConnectionError, Net::OpenTimeout
  
OAuth2::ConnectionError (Net::OpenTimeout):
  
lib/microsoft_graph_auth.rb:39:in `raw_info'
lib/microsoft_graph_auth.rb:32:in `block in <class:MicrosoftGraphAuth>'
E, [2023-02-01T17:08:55.698072 #68868] ERROR -- omniauth: (microsoft_graph_auth) Authentication failure! Net::OpenTimeout: OAuth2::ConnectionError, Net::OpenTimeout
  
OAuth2::ConnectionError (Net::OpenTimeout):
  
lib/microsoft_graph_auth.rb:39:in `raw_info'
lib/microsoft_graph_auth.rb:32:in `block in <class:MicrosoftGraphAuth>'`

<img width="979" alt="image" src="https://user-images.githubusercontent.com/65462425/216066224-af7366a2-4ed2-4b79-a33d-ea8568ce5364.png">

**Comment by Mohammed-Balfaqih** [comment]
@jasonjoh I tried to call from the:  https://developer.microsoft.com/en-us/graph/graph-explorer
and the call succeeded as well. so what do you think the issue will be? 🤔 

This is the logs if it can help:
`OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".
Started GET "/auth/microsoft_graph_auth/callback?code=M.R3_BAY.51cfdb67-748b-e3c3-9f23-c286c558ab20&state=72d207ce617bc770ecf66d55ed725ffe2d13f18cb1a3f5da" for ::1 at 2023-02-01 17:07:53 +0300
D, [2023-02-01T17:07:53.859309 #68868] DEBUG -- omniauth: (microsoft_graph_auth) Callback phase initiated.
OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".
E, [2023-02-01T17:08:29.384032 #68868] ERROR -- omniauth: (microsoft_graph_auth) Authentication failure! Net::OpenTimeout: OAuth2::ConnectionError, Net::OpenTimeout
  
OAuth2::ConnectionError (Net::OpenTimeout):
  
lib/microsoft_graph_auth.rb:39:in `raw_info'
lib/microsoft_graph_auth.rb:32:in `block in <class:MicrosoftGraphAuth>'
E, [2023-02-01T17:08:55.698072 #68868] ERROR -- omniauth: (microsoft_graph_auth) Authentication failure! Net::OpenTimeout: OAuth2::ConnectionError, Net::OpenTimeout
  
OAuth2::ConnectionError (Net::OpenTimeout):
  
lib/microsoft_graph_auth.rb:39:in `raw_info'
lib/microsoft_graph_auth.rb:32:in `block in <class:MicrosoftGraphAuth>'`

<img width="979" alt="image" src="https://user-images.githubusercontent.com/65462425/216067904-23752cda-e6b4-4d2e-aa75-898f6f71118d.png">

**Comment by jasonjoh** [comment]
Ruby version might be relevant as well. I'm using 3.1.2.
