### ISSUE TITLE
Why don't you have an example using msgraph ruby gem

### ISSUE THREAD

**Issue by dsisnero** [microsoftgraph/msgraph-sample-rubyrailsapp#93]
why don't you use https://github.com/microsoftgraph/msgraph-sdk-ruby in an example app?

**Comment by jasonjoh** [comment]
Thank you for your question @dsisnero! When this guide was originally written, the Ruby SDK wasn't available. Currently it is still in preview. We will be converting this to use the SDK as we get closer to an official release of the SDK.
